Use @typescript/no-useless-constructor
fibricheck/q-linting pull request #24
Opened 2022-02-04 14:28 UTC by AaronTrippaers

The current rule is broken for typescript constructors like the following one:

```
It allows following typescript constructors:

constructor(
    public dataService: DataServiceClient,
    public systemUserContext: Context,
    public measurementSchemaId: string,
    public startAnalysisTransitionId: string,
    public completeAnalysisTransitionId: string,
    public failAnalysisTransitionId: string,
    public cancelAnalysisTransitionId: string
  ) { }
  ```

This change fixes it.

2022-02-04 14:33 UTC, ThomasReyskens approved these changes

2022-02-10 17:47 UTC, wwaaijer-fib requested changes
I think we would also need a version number increase. Otherwise we're going to (try to) override the current version while publishing

2022-02-14 16:08 UTC, AaronTrippaers commented
> I think we would also need a version number increase. Otherwise we're going to (try to) override the current version while publishing

I did the version upgrade here and set all the base branches to dev. Will do a PR to master once the 3 PR's are merged.

2022-02-15 13:23 UTC, wwaaijer-fib approved these changes

2022-02-15 15:09 UTC, merged